@startuml
object Patient{
    <u>id_patient</u>
    nom
    prenom
    email
    mdp
}

object Proche{
    <u>id_proche</u>
    nom
    prenom
    email
    tel
    lien
    id_patient
}

object Medecin{
    <u>id_medecin</u>
    nom
    prenom
    adresse
    email
    tel
    id_patient
}

object Mesure{
    date_prise
    niveau_glycémie
    quantité_injection
    id_patient
}

object Recette{
    <u>id_recette</u>
    description
    image
}

object Cas_Urgent {
    id_proche
    id_patient
}

Patient --- Cas_Urgent : id_patient
Patient --- Medecin : id_patient
Patient --- Mesure : id_patient
Cas_Urgent --- Proche : id_proche

@enduml
